## Neuron: The building block of deep learning

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Now we will create a fake 'data'
data = np.arange(24).reshape(8, 3)
print(data)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [3]:
# Now we will create a 'neuron' and calculate the 'output'
neuron = tf.keras.layers.Dense(1)
output = neuron(data)

In [4]:
# Let's see what are the 'weights' and 'bias' of neuron
weights = neuron.kernel.numpy()
bias = neuron.bias.numpy()

In [5]:
weights

array([[ 0.7330694 ],
       [ 0.92575157],
       [-0.5437012 ]], dtype=float32)

In [8]:
weights.shape

(3, 1)

There are three columns in our input 'data' that's why 'weights' also have 3 values (or 3 rows)

In [6]:
bias

array([0.], dtype=float32)

In [7]:
bias.shape

(1,)

In [7]:
# This is tensorflow's output of neuron
output.numpy()

array([[ 2.001583 ],
       [ 6.2585363],
       [10.51549  ],
       [14.772442 ],
       [19.029396 ],
       [23.28635  ],
       [27.543303 ],
       [31.800255 ]], dtype=float32)

In [8]:
# Let's caluclate the above output on our own!
our_output = np.dot(data, weights) + bias

In [9]:
our_output.astype(np.float32)

array([[ 2.001583 ],
       [ 6.2585363],
       [10.51549  ],
       [14.772443 ],
       [19.029396 ],
       [23.28635  ],
       [27.543303 ],
       [31.800257 ]], dtype=float32)

This is exact output as Tensorflow!